### ISSUE TITLE
Rvm incorrect gem path being opened

### ISSUE THREAD

**Issue by toyhammered** [gurgeous/vscode-ruby-open-gem#1]
## Description
It seems that because I am using rvm it isn't able to properly find the correct game via the gemset.

`bundle list --paths` shows:
`/Users/<name>/.rvm/gems/ruby-2.7.3@<gemset-name>/gems/actioncable-6.1.7.2`

When I use the extension and click on `actioncable-6.1.7.2` it opens the below path
`/Users/<name>/.rvm/gems/ruby-3.2.0/gems/actioncable-6.1.7.2`

**Comment by gurgeous** [comment]
Thanks for the report! If you open a vscode terminal and type `bundle list --paths` which do you see? Sounds like maybe vscode and your regular terminal have different ideas about which ruby to use. Just a guess!

**Comment by toyhammered** [comment]
The above paths you see are from my vscode terminal. Here are a few more.
```
/Users/<name>/.rvm/gems/ruby-2.7.3@<gemset-name>/gems/actioncable-6.1.7.2
/Users/<name>/.rvm/gems/ruby-2.7.3@<gemset-name>/gems/actionmailbox-6.1.7.2
/Users/<name>/.rvm/gems/ruby-2.7.3@<gemset-name>/gems/actionmailer-6.1.7.2
```

**Comment by toyhammered** [comment]
Just restarted vscode entirely and it solved itself. Sorry about that!

**Comment by gurgeous** [comment]
No worries, these issues are extremely tricky to debug! It's not easy to convince vscode to use the right ruby... I run into problems like this all the time, unfortunately.
